version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
file_exists_behavior: OVERWRITE
    
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root
      
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
      
  
